services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: ApiGateway
      dockerfile: Dockerfile

  todolist:
    image: ${DOCKER_REGISTRY-}todolist
    build:
      context: TodoList
      dockerfile: Dockerfile

