services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: ApiGateway
      dockerfile: Dockerfile

  todolist:
    image: ${DOCKER_REGISTRY-}todolist
    build:
      context: TodoList
      dockerfile: Dockerfile


  user:
    image: ${DOCKER_REGISTRY-}user
    build:
      context: User
      dockerfile: Dockerfile

