services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todolist
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=todolist;Username=todo;Password=todo
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: